name: CI
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      run: |
          npm run ci
          git config --global user.name 'git-action'
          git config --global user.email 'git-action@users.noreply.github.com'
          git add .
          git commit -m "auto format"
          git push
        
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        BRANCH: gh-pages
        FOLDER: docs/.vuepress/dist
