name: CI
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: build
      run: |
          npm run ci

    - name: push
      run: |
          git config --global user.name 'git-action'
          git config --global user.email 'git-action@users.noreply.github.com'
          git add .
          git status | grep "nothing to commit1" && git commit -m "auto format" && git push
          
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        BRANCH: gh-pages
        FOLDER: docs/.vuepress/dist
