name: CI
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
        
    - name: Install and Build
      run: |
        npm run ci
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        BRANCH: gh-pages
        FOLDER: docs
